// Generates ../../control-plane/live.html: the operator control plane wired
// to the REAL reference implementation, bundled inline so the page works from
// file:// (browsers block external module imports on the null origin, so the
// bundle is embedded, not referenced). Commit the generated file; users never
// need to run this build.

import { buildSync } from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const entry = path.join(here, "..", "src", "index.ts");
const outFile = path.join(here, "..", "..", "control-plane", "live.html");

const bundle = buildSync({
  entryPoints: [entry],
  bundle: true,
  format: "iife",
  globalName: "MeterlessWorldModel",
  platform: "browser",
  write: false,
  alias: {
    "node:fs": path.join(here, "browser-stubs", "fs.ts"),
    "node:path": path.join(here, "browser-stubs", "path.ts"),
  },
}).outputFiles[0].text;

const app = fs.readFileSync(path.join(here, "live-app.js"), "utf-8");

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>World Model Control Plane (live)</title>
  <style>
    :root { --bg: #0d0d0d; --surface: #161616; --border: rgba(255,255,255,0.08); --text: #f5f5f5; --text-muted: rgba(245,245,245,0.6); --accent: #18E299; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; background: var(--bg); color: var(--text); line-height: 1.5; }
    header { padding: 1rem 1.5rem; border-bottom: 1px solid var(--border); display: flex; align-items: center; justify-content: space-between; }
    header h1 { font-size: 16px; font-weight: 500; }
    .role-pill { font-size: 12px; padding: 4px 10px; border: 1px solid var(--border); border-radius: 999px; color: var(--text-muted); }
    main { display: grid; grid-template-columns: 220px 1fr; height: calc(100vh - 88px); }
    nav { border-right: 1px solid var(--border); padding: 1rem 0.5rem; }
    nav button { display: block; width: 100%; text-align: left; background: transparent; color: var(--text-muted); border: none; padding: 8px 12px; font-size: 14px; cursor: pointer; border-radius: 6px; font-family: inherit; }
    nav button:hover { background: var(--surface); color: var(--text); }
    nav button.active { background: var(--surface); color: var(--accent); }
    section { padding: 1.5rem; overflow-y: auto; }
    section h2 { font-size: 18px; font-weight: 500; margin-bottom: 0.5rem; }
    section p.lede { color: var(--text-muted); margin-bottom: 1.5rem; }
    .panel { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1rem 1.25rem; margin-bottom: 1rem; }
    .panel h3 { font-size: 14px; font-weight: 500; margin-bottom: 0.5rem; }
    .panel pre { font-family: 'Geist Mono', ui-monospace, monospace; font-size: 12px; color: var(--text-muted); white-space: pre-wrap; }
    .empty { color: var(--text-muted); font-style: italic; padding: 2rem; text-align: center; border: 1px dashed var(--border); border-radius: 8px; }
    .btn { background: var(--accent); color: #0d0d0d; border: none; border-radius: 6px; padding: 6px 12px; font-size: 12px; cursor: pointer; margin-right: 8px; font-family: inherit; }
    .btn.ghost { background: transparent; color: var(--text-muted); border: 1px solid var(--border); }
    input, select { background: var(--bg); border: 1px solid var(--border); color: var(--text); border-radius: 6px; padding: 6px 10px; font-size: 13px; font-family: inherit; margin-right: 8px; }
    .muted { font-size: 12px; color: var(--text-muted); margin-top: 8px; }
  </style>
</head>
<body>
  <header>
    <h1>World Model — Control Plane (live)</h1>
    <span class="role-pill" id="role">Role: Admin</span>
  </header>
  <div style="background: rgba(24, 226, 153, 0.08); border-bottom: 1px solid var(--border); padding: 6px 1.5rem; font-size: 12px; color: var(--text-muted);">
    Live: this page runs the actual reference implementation (bundled inline, storage in memory, seeded data). Generated by <code>reference/scripts/build-browser-bundle.ts</code>. The static contract mock is <code>index.html</code>.
  </div>
  <main>
    <nav>
      <button class="active" data-panel="inspect">Inspect</button>
      <button data-panel="merge">Merge</button>
      <button data-panel="edit">Edit</button>
      <button data-panel="rebuild">Rebuild</button>
      <button data-panel="repair">Repair</button>
      <button data-panel="audit">Audit log</button>
    </nav>
    <section id="content"></section>
  </main>
  <script>
${bundle}
  </script>
  <script>
${app}
  </script>
</body>
</html>
`;

fs.writeFileSync(outFile, html, "utf-8");
console.log(`wrote ${outFile} (${(html.length / 1024).toFixed(0)} KB)`);
